# SwiftLint Configuration File

excluded:
  - Carthage
  - Pods
  - fastlane
  - DerivedData

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - last_where
  - sorted_imports
  - toggle_bool
  - yoda_condition
  - multiline_parameters
  - multiline_arguments

disabled_rules:
  - force_cast
  - force_try
  - identifier_name
  - line_length
  - type_body_length
  - function_body_length

analyzer_rules:
  - unused_import

line_length: 120

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 60
  error: 100

cyclomatic_complexity: 
  warning: 10
  error: 20

